### ISSUE TITLE
Query wallet returns UNKNOWN error

### ISSUE THREAD

**Issue by Guy-Heylens-Elia** [project-origin/wallet#108]
### Description

Hello,

We are sending issueCertificate commands to the Registry without any issue now. 
After that we send the info to wallet (cfr WithWalletExample) and try to query the Wallet.

Basically this is the WithWalletFlow example we are trying to execute against our environment.

When trying to query the wallet we receive a gRPC error with status UNKNOWN back, and I do not see anything in the logs of the Wallet?  
![gRPC-QueryGranular-error](https://github.com/project-origin/wallet/assets/104833610/f1f07d2b-ebfc-4a23-856f-5cc1f0ae7559)

When we try to invoke the Wallet QueryGranularCertificates with another bearer token we get an empty result back:
![image](https://github.com/project-origin/wallet/assets/104833610/9c0de48a-17bd-4559-9e2d-63f95d7120c8)

And in the logs on K8S we see the call: 
![image](https://github.com/project-origin/wallet/assets/104833610/fac6514a-447c-43fd-b073-1c76b6ea8847)

**Comment by MartinSchmidt** [comment]
@Guy-Heylens-Elia could you share the log as json, as i cant see the entire message, and is that the query log from the empty success or the failed request?

**Comment by Guy-Heylens-Elia** [comment]
This is the log of a successful call, but an empty list: 
[wallet-dev-logs-empty-list.txt](https://github.com/project-origin/wallet/files/12813034/wallet-dev-logs-empty-list.txt)

**Comment by Guy-Heylens-Elia** [comment]
This is the log of a failing Query:
[wallet-dev-logs-query-error.txt](https://github.com/project-origin/wallet/files/12813055/wallet-dev-logs-query-error.txt)

**Comment by MartinSchmidt** [comment]
@Guy-Heylens-Elia  which version of the wallet are you using?

**Comment by Guy-Heylens-Elia** [comment]
Hello Martin,

The version we have implemented is as follows: Registry 0.2.2 and the Wallet 0.2.0

**Comment by MartinSchmidt** [comment]
@Guy-Heylens-Elia  found the bug and have released a [new version](https://github.com/project-origin/wallet/releases/tag/v0.2.1)
