### ISSUE TITLE
Translate public_key to ownerKey

### ISSUE THREAD

**Issue by Guy-Heylens-Elia** [project-origin/wallet#111]
### Description

Hello,

We would like to have a solution for the following problem.

Our users will execute the CreateWalletDepositEndpoint and receive their public_key in the payload:
![image](https://github.com/project-origin/wallet/assets/104833610/11a1af57-ed75-4997-9a92-abc6a2d886bd)

After that they will create a Contract in our endpoints with the public_key, we will store the public_key as a string in our db. Every time the contract is triggered to generate GranularCertificates we will use that public_key to convert it to the ownerKey to create the IssuedEvent (cfr WithWalletFlow example).

Would it be possible to provide some information on how to convert the public_key (stored as string) to ownerKey (Hierarchical  Deterministic key)? Or update the existing flow to use/accept the public_key from the payload of the CreateWalletDepositEndpoint.
![image](https://github.com/project-origin/wallet/assets/104833610/478b5353-4c24-4b39-9c5b-97c6493c467a)

Thanks

**Comment by MartinSchmidt** [comment]
@Guy-Heylens-Elia  sure, a quick write up would be:

```csharp
var stringPublicKey = "AYNyD20AAAABJQpeaa8HC39R8PswEdfADxxmB46XjPSNyJaxDZ8ShjQD/edUV+q+76an1vKuGXs7APkcIiP6ukLR4eL9SQlwwjI=";
var publicHDkey = Algorithms.Secp256k1.ImportHDPublicKey(Convert.FromBase64String(stringPublicKey));
var nextPosition = 5;
var ownerKey = publicHDkey.Derive(nextPosition);
```

**Comment by Guy-Heylens-Elia** [comment]
@MartinSchmidt  is the nextPosition a fixed value? And why does it have to be 5?

var nextPosition = 5;

**Comment by MartinSchmidt** [comment]
@Guy-Heylens-Elia, no it should be an incremented each time you use the publicKey to send something to it, and each position should not be reused for a publicKey, and the position must be between 0 and int32 max.

**Comment by MartinSchmidt** [comment]
I will try to get around to write some more concrete documentation on this subject.
