### ISSUE TITLE
Pagination and search for certificate REST endpoint

### ISSUE THREAD

**Issue by ckr123** [project-origin/wallet#177]
### Description

We would like to be able to paginate certificates and be able to search on specific certificates based on time, meteringpoint or type of certificate(production/consumption).
As our frontend is using it rigth now, we would like it to be a non-breaking change.

**Comment by MartinSchmidt** [comment]
@ckr123 I have some questions for how you toughs are on pagenation.

Should pagenation be stabel while paging? 
example: if you have 24 items on 3 pages, and a new one is inserted into the database while changing page.
- should it be included in the results? and result in items might move on the pages? 
- or should it keep returning only results for the 24 items, until a new initial request is made?
