### ISSUE TITLE
OpenTelemetry Traces

### ISSUE THREAD

**Issue by sahma19** [project-origin/wallet#201]
### Description

Currently EnergyOrigin is using Opentelemetry for collecting traces and metrics, and exporting them to Prometheus and Jaeger Respectively, via the OTEL-Collector. This has allowed us to achieve higher observability, by being able to propagate the spans and traces across the different services hosted in the cluster. 

Given that the wallet is currently hosted in the same cluster (for now), I suggest enabling metrics and traces to be exported to the same OpenTelemetry Collector, we are using. I also noticed that the Registry is currently exporting metrics to our collector, so why not let the wallet do the same? I have posted an example on how to make this possible. I do not mind submitting a PR on this myself, if that is what it takes.

### Basic Example

![image](https://github.com/project-origin/wallet/assets/55732914/6627e23e-c3ea-4f51-9e56-15b035ee36fe)

An example can be found here as well: [https://github.com/Energinet-DataHub/energy-origin/blob/main/domains/transfer/Transfer.API/API/Program.cs](url)

### Drawbacks

Currently Services like the Wallet and the Registry are enriching logs with a span and traceId, which doesn't provide a lot of value, if we don't export the traces as well. 

### Etc

I can open a PR, with the necessary changes to the Wallet service, if that is wanted.

**Comment by MartinSchmidt** [comment]
Implemented by #204
