### ISSUE TITLE
scopes on wallet apis

### ISSUE THREAD

**Issue by MartinSchmidt** [project-origin/wallet#219]
```[tasklist]
### Tasks
```

**Comment by sahma19** [comment]
Scopes for endpoints (Work in Progress):

POST api/v1/wallets: wallet:create
Scope Description: Allows creating a new wallet.

GET api/v1/wallets: wallet:read_all
Scope Description: Allows retrieving all wallets associated with the user.

GET api/v1/wallets/{walletId}: wallet:read
Scope Description: Allows retrieving a specific wallet associated with the user.

POST api/v1/wallets/{walletId}/endpoints: wallet:endpoint:create
Scope Description: Allows creating a new endpoint on the user's wallet.

POST api/v1/external-endpoints: external_endpoint:create
Scope Description: Allows creating a new external endpoint for the user.
