### ISSUE TITLE
Verify slices batchjob

### ISSUE THREAD

**Issue by tnickelsen** [project-origin/wallet#26]
# Description
When the wallet receives a slice, it needs to verify the ownership information from a registry and insert Granular certificate header. This is done via a batch job verifying all slices.

## Acceptance criteria
- ReceivedSlices are converted to Slices in the database

## Scope limit
- Verification to Project Origin is out of this scope #5 

## Solution plan
- [x] Setup BackgroundService
- [x] Read ReceivedSlices 
- [x] Convert ReceivedSlices to Slices
- [ ] Document functionality
- [x] Write test

**Comment by duizer** [comment]
Documentation not done, but will be part of #5
