### ISSUE TITLE
Protobuf files available for generating clients

### ISSUE THREAD

**Issue by tnickelsen** [project-origin/wallet#32]
# Description
Protobuf files are used for gRPC contract for server and client. Right now .proto files are implemented by the server, but clients needs to implement them as well in order to call the server. Thus the .proto files needs to be distributed/availble to/fer server and clients. 

One approach is using references to tags in Github repository.
Another is via nuget. See links:

- https://github.com/grpc/grpc-dotnet/issues/183
- https://github.com/dotnet/aspnetcore/pull/44999
- https://stackoverflow.com/questions/66844211/sharing-one-grpc-proto-file-for-all-solutions

## Acceptance criteria

- Documentation updated with how to generate a client

## Solution plan

**Comment by duizer** [comment]
Martin prefers a solution where client projects refer to the protobuf-files in tags in this github repo
