### ISSUE TITLE
Transfer certificates api endpoint

### ISSUE THREAD

**Issue by tnickelsen** [project-origin/wallet#36]
### Description
Transfer certificates to wallet section reference

### Acceptance Criteria
- Protobuf api endpoint for transferring certificates that returns 200

### Out of scope
- Transfers doesn't happen
- No connection to the registry

### Solution Plan 
- [ ] Write protobuf contract
- [ ] Implement contract without connection to the registry

**Comment by MartinSchmidt** [comment]
Closed by #44
