### ISSUE TITLE
Query claims

### ISSUE THREAD

**Issue by MartinSchmidt** [project-origin/wallet#42]
# Description
As the owner of a wallet I want to be able to view the claims i have already made through my wallet

## Acceptance criteria
- API can return the claims in the wallet.
- Integrations tests

Example request:
```json

{
  "filter": {
    "fromDate": "2023-01-01T00:00:00Z", 
    "toDate": "2023-01-01T01:00:00Z"
  }
}
```
Example response: 
```json
[
  {
    "fromDate": "2023-01-01T00:00:00Z", 
    "toDate": "2023-01-01T01:00:00Z",
    "attributes":  {
      "tech": "wind"
     },
    "amount": 124,
  },
  {
    "fromDate": "2023-01-01T00:00:00Z", 
    "toDate": "2023-01-01T01:00:00Z",
    "attributes": {
      "tech": "solar"
     },
    "amount": 235,
  },
]
```

## Solution plan
- [ ] Add API to query Claims

**Comment by duizer** [comment]
For inspiration on the query requirements from EnergyOrigin, see https://app.zenhub.com/workspaces/team-atlas-633199659e255a37cd1d144f/issues/gh/energinet-datahub/energy-origin-issues/1454

**Comment by MartinSchmidt** [comment]
@duizer i don't have access to that like, so could you please provide the information here.
