### ISSUE TITLE
CreateReceiverDepositEndpoint endpoint

### ISSUE THREAD

**Issue by tnickelsen** [project-origin/wallet#45]
### Description
Before being able to send certificates/slices from wallet to wallet we the receiver deposit endpoint must be created, which is where the certificates are sent to.

### Acceptance Criteria
- When called a guid is returned to the sender, which states where to send the certificates to

### Out of scope
See comment below (https://github.com/project-origin/wallet/issues/45#issuecomment-1630683667)

### Solution Plan
- [x] Rename WalletSections table to DepositEndpoint 
- [x] Make WalletId and WalletPosition nullable for receiverDepositEndpoints and add owner and referenceText
- [x] Create and store receiver deposit endpoint in database
- [x] Migrations for Owner so that it is non-nullable and gets owner from Wallet table
- [x] Migrations for referenceText to string.empty
- [x] Write integration tests

**Comment by duizer** [comment]
What about verification that the Wallet Deposit Endpoint is working? That is, it is referencing a working Wallet System and can hit a valid Wallet. 
As far as I can see, this is outside the scope of this task. Should we have an issue for it?
