### ISSUE TITLE
Exposing the wallet API

### ISSUE THREAD

**Issue by duizer** [project-origin/wallet#51]
The functionality of the wallet will be exposed through Energy Origin and Elia. Since we want our APIs to be aligned, we should agree upon how the wallet functionality is exposed.

- Do we do it directly, so clients can use the GRPC interface of the Wallet?
- Do we create a REST interface on top of the Wallet GRPC interface?
- Do we have our own abstraction layer that maps to the Wallet interface?
- Do we ...

**Comment by michaelpiron** [comment]
Hi all (@duizer , @MartinSchmidt @wisbech )
cc @Mike4Elia @inassbelgcir @guyheylens @Kingaday 

Paul's questions above are popping up as well in our Elia team as we are refining the integration effort.
Should we build our own intermediate service that accepts REST API commands, which then talks to the wallet service gRPC interface?

Additionally:
* How will a wallet service at provider A interact with registry service at issuing body B
* How will a wallet service at provider A interact with wallet service at provider C (in case of a slice transfer)
* How will different registries interact (in case of a cross-border claim)

**Comment by MartinSchmidt** [comment]
In the long run i personally believe it would be best to expose either the gRPC of the wallet or create a REST based API for this purpose, if each implementation creates a intermediate services, the change drift increases, and so for third parties to interact with them greatly diminishes as they would need implement different implementations for each wallet hoster.
