### ISSUE TITLE
Creating multiple Wallet Deposit Endpoints at the same time fails when Wallet does not exist

### ISSUE THREAD

**Issue by duizer** [project-origin/wallet#60]
### Describe the Bug

Concurrent call to create a Wallet Deposit Endpoint (or a Wallet for that sake) fails. The reason is that a Wallet will be automatically created if it does not exist and there is a uniqueness constraint on the owner. 
The code will try to create multiple wallets with the same owner, but only 1 will succeed and the other will fail. The code then throws an exception for the failing calls. 

### To Reproduce

```bash
1.
2.
3.
...
```

### Expected Behavior

Does not fail

### Desktop

...

**Comment by MartinSchmidt** [comment]
fixed by #237
