### ISSUE TITLE
Enabling gRPC server reflection

### ISSUE THREAD

**Issue by InassBelgcir** [project-origin/wallet#85]
### Description

Could not get service definition when choosing service reflection option on postman. 

![image](https://github.com/project-origin/wallet/assets/141126356/7265908c-7e97-4c7e-9d52-60e96b22d67d)

logs : 
![image](https://github.com/project-origin/wallet/assets/141126356/18b54d23-0280-4ab1-bed4-453cbbbc5694)

**Comment by MartinSchmidt** [comment]
@InassBelgcir REST as been an ongoing topic, and #170 has been created, as all APIs will be available as REST, and gRPC might then actually become deprecated, as it seams most users prefer that solution, can we close this issue?

**Comment by MartinSchmidt** [comment]
gRPC in the wallet, are slated for deprecation.
